#!/bin/bash
export BERT_CHECKPOINT =
export BERT_VOCAB = 
export BERT_CONFIG = 
CUDA_VISIBLE_DEVICES=0 python3 MRC_NER.py  \
        --task_name="ner"  \
        --do_train=True  \
        --do_eval=True   \
        --do_predict=True \
        --data_dir=../data/data_guideline_query_extend   \
        --vocab_file=$BERT_VOCAB \
        --bert_config_file=$BERT_CONFIG \
        --init_checkpoint=$BERT_CHECKPOINT \
        --max_seq_length=250   \
        --train_batch_size=20  \
        --learning_rate=2e-5 \
        --other_learning_rate=2e-5  \
        --num_train_epochs=20 \
        --output_dir=./output_v3_rc_guideline_query_extend